/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author loith
 */
public class leftMenuQuanLy extends javax.swing.JPanel {
    Color  matteBlue = new Color(14,142,233);  
    Color  matteGrey = new Color(223,230,233);
    Color  normalBlack = new Color(51,51,51);
    /**
     * Creates new form leftMenuAdmin
     */
    ShopForm shop;
    public leftMenuQuanLy(JFrame mainFrame) {
        initComponents();
        leftMenuScrollPane.getVerticalScrollBar().setUnitIncrement(8);
        shop = (ShopForm) mainFrame;
    }
    
    void setBtnBg(JButton btn)
    {
        btn.setBackground(Color.WHITE);
        btn.setForeground(matteBlue);
    }
    
    void resetBtnBg(JButton btn)
    {
        btn.setBackground(matteGrey);
        btn.setForeground(normalBlack);
    }
    
    void setDedaultBtn()
    {
       resetBtnBg(btnBanHangAdmin);
       resetBtnBg(btnNhapHangAdmin);
       resetBtnBg(btnSanPhamAdmin);
       resetBtnBg(btnNhanVienAdmin);
       resetBtnBg(btnKhachHangAdmin);
       resetBtnBg(btnNhaCungCapAdmin);
       resetBtnBg(btnKhuyenMaiAdmin);
       resetBtnBg(btnNhaSanXuatAdmin);
       resetBtnBg(btnLoaiSPAdmin);
       resetBtnBg(btnThongKeAdmin);
       resetBtnBg(btnTimNangCaoAdmin);
    }
    
    void setSelectedBtn(JButton btn)
    {
       setDedaultBtn();
       setBtnBg(btn);
    }
    void setSelectedButton(String str)
    {
        setDedaultBtn();
        switch (str)
        {
            case "Bán hàng": setBtnBg(btnBanHangAdmin);
            break;
            
            case "Nhập Hàng": setBtnBg(btnNhapHangAdmin);
            break;
            
            case "Sản Phẩm": setBtnBg(btnSanPhamAdmin);
            break;
            
            case "Loại Sản Phẩm": setBtnBg(btnLoaiSPAdmin);
            break;
            
            case "Nhân Viên": setBtnBg(btnNhanVienAdmin);
            break;
            
            case "Khách Hàng": setBtnBg(btnKhachHangAdmin);
            break;
            
            case "Nhà Cung Cấp": setBtnBg(btnNhaCungCapAdmin);
            break;
            
            case "Nhà Sản Xuất": setBtnBg(btnNhaSanXuatAdmin);
            break;
            
            case "Khuyến Mãi": setBtnBg(btnKhuyenMaiAdmin);
            break;
            
            case "Thống Kê": setBtnBg(btnThongKeAdmin);
            break;
            
            case "Tìm Nâng Cao": setBtnBg(btnTimNangCaoAdmin);
            break;
        }
    }
    void setScroll(int vertical)
    {
        scroll(vertical, leftMenuScrollPane);
    }
    public void scroll(int vertical, JScrollPane scroll) {        
    switch (vertical) {
        case SwingConstants.TOP:
            scroll.getVerticalScrollBar().setValue(0);
            break;
        case SwingConstants.CENTER:
            scroll.getVerticalScrollBar().setValue(scroll.getVerticalScrollBar().getMaximum());
            scroll.getVerticalScrollBar().setValue(scroll.getVerticalScrollBar().getValue() / 2);
            break;
        case SwingConstants.BOTTOM:  
            scroll.getVerticalScrollBar().setValue(scroll.getVerticalScrollBar().getMaximum());
            break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftMenuScrollPane = new javax.swing.JScrollPane();
        pnlLeftMenu4 = new javax.swing.JPanel();
        btnBanHangAdmin = new javax.swing.JButton();
        btnNhapHangAdmin = new javax.swing.JButton();
        btnSanPhamAdmin = new javax.swing.JButton();
        btnNhanVienAdmin = new javax.swing.JButton();
        btnKhachHangAdmin = new javax.swing.JButton();
        btnNhaCungCapAdmin = new javax.swing.JButton();
        btnNhaSanXuatAdmin = new javax.swing.JButton();
        btnKhuyenMaiAdmin = new javax.swing.JButton();
        btnLoaiSPAdmin = new javax.swing.JButton();
        btnThongKeAdmin = new javax.swing.JButton();
        btnTimNangCaoAdmin = new javax.swing.JButton();

        leftMenuScrollPane.setBorder(null);
        leftMenuScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlLeftMenu4.setBackground(new java.awt.Color(255, 255, 255));

        btnBanHangAdmin.setBackground(new java.awt.Color(223, 230, 233));
        btnBanHangAdmin.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnBanHangAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnBanHangAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cart_icon_blue.png"))); // NOI18N
        btnBanHangAdmin.setText("Bán Hàng");
        btnBanHangAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnBanHangAdmin.setContentAreaFilled(false);
        btnBanHangAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBanHangAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBanHangAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBanHangAdmin.setIconTextGap(20);
        btnBanHangAdmin.setOpaque(true);
        btnBanHangAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBanHangAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBanHangAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBanHangAdminMouseExited(evt);
            }
        });
        btnBanHangAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangAdminActionPerformed(evt);
            }
        });

        btnNhapHangAdmin.setBackground(new java.awt.Color(223, 230, 233));
        btnNhapHangAdmin.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnNhapHangAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnNhapHangAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/note_icon_blue.png"))); // NOI18N
        btnNhapHangAdmin.setText("Nhập Hàng");
        btnNhapHangAdmin.setAlignmentX(0.5F);
        btnNhapHangAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnNhapHangAdmin.setContentAreaFilled(false);
        btnNhapHangAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhapHangAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnNhapHangAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNhapHangAdmin.setIconTextGap(15);
        btnNhapHangAdmin.setOpaque(true);
        btnNhapHangAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhapHangAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhapHangAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhapHangAdminMouseExited(evt);
            }
        });
        btnNhapHangAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHangAdminActionPerformed(evt);
            }
        });

        btnSanPhamAdmin.setBackground(new java.awt.Color(223, 230, 233));
        btnSanPhamAdmin.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnSanPhamAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnSanPhamAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/box_icon_blue.png"))); // NOI18N
        btnSanPhamAdmin.setText("Sản Phẩm");
        btnSanPhamAdmin.setAlignmentX(0.5F);
        btnSanPhamAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnSanPhamAdmin.setContentAreaFilled(false);
        btnSanPhamAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSanPhamAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSanPhamAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSanPhamAdmin.setIconTextGap(15);
        btnSanPhamAdmin.setOpaque(true);
        btnSanPhamAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSanPhamAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSanPhamAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSanPhamAdminMouseExited(evt);
            }
        });
        btnSanPhamAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamAdminActionPerformed(evt);
            }
        });

        btnNhanVienAdmin.setBackground(new java.awt.Color(223, 230, 233));
        btnNhanVienAdmin.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnNhanVienAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnNhanVienAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/assistant_icon_blue.png"))); // NOI18N
        btnNhanVienAdmin.setText("Nhân Viên");
        btnNhanVienAdmin.setAlignmentX(0.5F);
        btnNhanVienAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnNhanVienAdmin.setContentAreaFilled(false);
        btnNhanVienAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhanVienAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnNhanVienAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNhanVienAdmin.setIconTextGap(15);
        btnNhanVienAdmin.setOpaque(true);
        btnNhanVienAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhanVienAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhanVienAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhanVienAdminMouseExited(evt);
            }
        });
        btnNhanVienAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienAdminActionPerformed(evt);
            }
        });

        btnKhachHangAdmin.setBackground(new java.awt.Color(223, 230, 233));
        btnKhachHangAdmin.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnKhachHangAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnKhachHangAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customer_icon_blue.png"))); // NOI18N
        btnKhachHangAdmin.setText("Khách Hàng");
        btnKhachHangAdmin.setAlignmentX(0.5F);
        btnKhachHangAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnKhachHangAdmin.setContentAreaFilled(false);
        btnKhachHangAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKhachHangAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnKhachHangAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnKhachHangAdmin.setIconTextGap(15);
        btnKhachHangAdmin.setOpaque(true);
        btnKhachHangAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhachHangAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhachHangAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhachHangAdminMouseExited(evt);
            }
        });
        btnKhachHangAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangAdminActionPerformed(evt);
            }
        });

        btnNhaCungCapAdmin.setBackground(new java.awt.Color(223, 230, 233));
        btnNhaCungCapAdmin.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnNhaCungCapAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnNhaCungCapAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/provider_icon_blue.png"))); // NOI18N
        btnNhaCungCapAdmin.setText("Nhà Cung Cấp");
        btnNhaCungCapAdmin.setAlignmentX(0.5F);
        btnNhaCungCapAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnNhaCungCapAdmin.setContentAreaFilled(false);
        btnNhaCungCapAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhaCungCapAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnNhaCungCapAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNhaCungCapAdmin.setIconTextGap(15);
        btnNhaCungCapAdmin.setOpaque(true);
        btnNhaCungCapAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhaCungCapAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhaCungCapAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhaCungCapAdminMouseExited(evt);
            }
        });
        btnNhaCungCapAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaCungCapAdminActionPerformed(evt);
            }
        });

        btnNhaSanXuatAdmin.setBackground(new java.awt.Color(223, 230, 233));
        btnNhaSanXuatAdmin.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnNhaSanXuatAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnNhaSanXuatAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manufacturing_icon_blue.png"))); // NOI18N
        btnNhaSanXuatAdmin.setText("Nhà Sản Xuất");
        btnNhaSanXuatAdmin.setAlignmentX(0.5F);
        btnNhaSanXuatAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnNhaSanXuatAdmin.setContentAreaFilled(false);
        btnNhaSanXuatAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhaSanXuatAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnNhaSanXuatAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNhaSanXuatAdmin.setIconTextGap(15);
        btnNhaSanXuatAdmin.setOpaque(true);
        btnNhaSanXuatAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhaSanXuatAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhaSanXuatAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhaSanXuatAdminMouseExited(evt);
            }
        });
        btnNhaSanXuatAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaSanXuatAdminActionPerformed(evt);
            }
        });

        btnKhuyenMaiAdmin.setBackground(new java.awt.Color(223, 230, 233));
        btnKhuyenMaiAdmin.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnKhuyenMaiAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnKhuyenMaiAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sale_icon_blue.png"))); // NOI18N
        btnKhuyenMaiAdmin.setText("Khuyến Mãi");
        btnKhuyenMaiAdmin.setAlignmentX(0.5F);
        btnKhuyenMaiAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnKhuyenMaiAdmin.setContentAreaFilled(false);
        btnKhuyenMaiAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKhuyenMaiAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnKhuyenMaiAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnKhuyenMaiAdmin.setIconTextGap(15);
        btnKhuyenMaiAdmin.setOpaque(true);
        btnKhuyenMaiAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhuyenMaiAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhuyenMaiAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhuyenMaiAdminMouseExited(evt);
            }
        });
        btnKhuyenMaiAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhuyenMaiAdminActionPerformed(evt);
            }
        });

        btnLoaiSPAdmin.setBackground(new java.awt.Color(223, 230, 233));
        btnLoaiSPAdmin.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnLoaiSPAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnLoaiSPAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list_icon_blue.png"))); // NOI18N
        btnLoaiSPAdmin.setText("Loại Sản Phẩm");
        btnLoaiSPAdmin.setAlignmentX(0.5F);
        btnLoaiSPAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnLoaiSPAdmin.setContentAreaFilled(false);
        btnLoaiSPAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoaiSPAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnLoaiSPAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLoaiSPAdmin.setIconTextGap(15);
        btnLoaiSPAdmin.setOpaque(true);
        btnLoaiSPAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoaiSPAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoaiSPAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoaiSPAdminMouseExited(evt);
            }
        });
        btnLoaiSPAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiSPAdminActionPerformed(evt);
            }
        });

        btnThongKeAdmin.setBackground(new java.awt.Color(223, 230, 233));
        btnThongKeAdmin.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnThongKeAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnThongKeAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chart_icon_blue.png"))); // NOI18N
        btnThongKeAdmin.setText("Thống Kê");
        btnThongKeAdmin.setAlignmentX(0.5F);
        btnThongKeAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnThongKeAdmin.setContentAreaFilled(false);
        btnThongKeAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongKeAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnThongKeAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThongKeAdmin.setIconTextGap(15);
        btnThongKeAdmin.setOpaque(true);
        btnThongKeAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongKeAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThongKeAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongKeAdminMouseExited(evt);
            }
        });
        btnThongKeAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeAdminActionPerformed(evt);
            }
        });

        btnTimNangCaoAdmin.setBackground(new java.awt.Color(223, 230, 233));
        btnTimNangCaoAdmin.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnTimNangCaoAdmin.setForeground(new java.awt.Color(51, 51, 51));
        btnTimNangCaoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/advanced_search_blue.png"))); // NOI18N
        btnTimNangCaoAdmin.setText("Tìm Nâng Cao");
        btnTimNangCaoAdmin.setAlignmentX(0.5F);
        btnTimNangCaoAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btnTimNangCaoAdmin.setContentAreaFilled(false);
        btnTimNangCaoAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimNangCaoAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnTimNangCaoAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTimNangCaoAdmin.setIconTextGap(15);
        btnTimNangCaoAdmin.setOpaque(true);
        btnTimNangCaoAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimNangCaoAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTimNangCaoAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTimNangCaoAdminMouseExited(evt);
            }
        });
        btnTimNangCaoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimNangCaoAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLeftMenu4Layout = new javax.swing.GroupLayout(pnlLeftMenu4);
        pnlLeftMenu4.setLayout(pnlLeftMenu4Layout);
        pnlLeftMenu4Layout.setHorizontalGroup(
            pnlLeftMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftMenu4Layout.createSequentialGroup()
                .addComponent(btnNhanVienAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlLeftMenu4Layout.createSequentialGroup()
                .addGroup(pnlLeftMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLeftMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlLeftMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnNhapHangAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSanPhamAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLoaiSPAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(btnBanHangAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftMenu4Layout.createSequentialGroup()
                            .addComponent(btnNhaCungCapAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(272, 272, 272)))
                    .addGroup(pnlLeftMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnTimNangCaoAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThongKeAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKhuyenMaiAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                        .addComponent(btnNhaSanXuatAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnKhachHangAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLeftMenu4Layout.setVerticalGroup(
            pnlLeftMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftMenu4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBanHangAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNhapHangAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSanPhamAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLoaiSPAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNhanVienAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnKhachHangAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNhaCungCapAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNhaSanXuatAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnKhuyenMaiAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnThongKeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTimNangCaoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        leftMenuScrollPane.setViewportView(pnlLeftMenu4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftMenuScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftMenuScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBanHangAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangAdminMouseClicked

    }//GEN-LAST:event_btnBanHangAdminMouseClicked

    private void btnBanHangAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangAdminMouseEntered

    }//GEN-LAST:event_btnBanHangAdminMouseEntered

    private void btnBanHangAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangAdminMouseExited

    }//GEN-LAST:event_btnBanHangAdminMouseExited

    private void btnBanHangAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangAdminActionPerformed
        
        shop.change("Bán hàng");
        setSelectedBtn(btnBanHangAdmin);
        shop.setReturnIcon();
         
    }//GEN-LAST:event_btnBanHangAdminActionPerformed

    private void btnNhapHangAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapHangAdminMouseClicked

    }//GEN-LAST:event_btnNhapHangAdminMouseClicked

    private void btnNhapHangAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapHangAdminMouseEntered

    }//GEN-LAST:event_btnNhapHangAdminMouseEntered

    private void btnNhapHangAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapHangAdminMouseExited

    }//GEN-LAST:event_btnNhapHangAdminMouseExited

    private void btnNhapHangAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapHangAdminActionPerformed
       shop.change("Nhập Hàng");
       setSelectedBtn(btnNhapHangAdmin);
       shop.setReturnIcon();
    }//GEN-LAST:event_btnNhapHangAdminActionPerformed

    private void btnSanPhamAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanPhamAdminMouseClicked

    }//GEN-LAST:event_btnSanPhamAdminMouseClicked

    private void btnSanPhamAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanPhamAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSanPhamAdminMouseEntered

    private void btnSanPhamAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanPhamAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSanPhamAdminMouseExited

    private void btnSanPhamAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamAdminActionPerformed
        shop.change("Sản Phẩm");
        setSelectedBtn(btnSanPhamAdmin);
        shop.setReturnIcon();
    }//GEN-LAST:event_btnSanPhamAdminActionPerformed

    private void btnNhanVienAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienAdminMouseClicked

    }//GEN-LAST:event_btnNhanVienAdminMouseClicked

    private void btnNhanVienAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienAdminMouseEntered

    }//GEN-LAST:event_btnNhanVienAdminMouseEntered

    private void btnNhanVienAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienAdminMouseExited

    }//GEN-LAST:event_btnNhanVienAdminMouseExited

    private void btnNhanVienAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienAdminActionPerformed
        shop.change("Nhân Viên");
        setSelectedBtn(btnNhanVienAdmin);
        shop.setReturnIcon();
    }//GEN-LAST:event_btnNhanVienAdminActionPerformed

    private void btnKhachHangAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangAdminMouseClicked

    }//GEN-LAST:event_btnKhachHangAdminMouseClicked

    private void btnKhachHangAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKhachHangAdminMouseEntered

    private void btnKhachHangAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKhachHangAdminMouseExited

    private void btnKhachHangAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangAdminActionPerformed
        shop.change("Khách Hàng");
        setSelectedBtn(btnKhachHangAdmin);
        shop.setReturnIcon();
    }//GEN-LAST:event_btnKhachHangAdminActionPerformed

    private void btnNhaCungCapAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhaCungCapAdminMouseClicked

    }//GEN-LAST:event_btnNhaCungCapAdminMouseClicked

    private void btnNhaCungCapAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhaCungCapAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhaCungCapAdminMouseEntered

    private void btnNhaCungCapAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhaCungCapAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhaCungCapAdminMouseExited

    private void btnNhaCungCapAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaCungCapAdminActionPerformed
        shop.change("Nhà Cung Cấp");
        setSelectedBtn(btnNhaCungCapAdmin);
        shop.setReturnIcon();
    }//GEN-LAST:event_btnNhaCungCapAdminActionPerformed

    private void btnNhaSanXuatAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhaSanXuatAdminMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnNhaSanXuatAdminMouseClicked

    private void btnNhaSanXuatAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhaSanXuatAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhaSanXuatAdminMouseEntered

    private void btnNhaSanXuatAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhaSanXuatAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhaSanXuatAdminMouseExited

    private void btnNhaSanXuatAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaSanXuatAdminActionPerformed
        // TODO add your handling code here:
        shop.change("Nhà Sản Xuất");
        setSelectedBtn(btnNhaSanXuatAdmin);
        shop.setReturnIcon();
    }//GEN-LAST:event_btnNhaSanXuatAdminActionPerformed

    private void btnKhuyenMaiAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhuyenMaiAdminMouseClicked

    }//GEN-LAST:event_btnKhuyenMaiAdminMouseClicked

    private void btnKhuyenMaiAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhuyenMaiAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKhuyenMaiAdminMouseEntered

    private void btnKhuyenMaiAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhuyenMaiAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKhuyenMaiAdminMouseExited

    private void btnKhuyenMaiAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhuyenMaiAdminActionPerformed
        // TODO add your handling code here:
        shop.change("Khuyến Mãi");
        setSelectedBtn(btnKhuyenMaiAdmin);
        shop.setReturnIcon();
    }//GEN-LAST:event_btnKhuyenMaiAdminActionPerformed

    private void btnLoaiSPAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoaiSPAdminMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnLoaiSPAdminMouseClicked

    private void btnLoaiSPAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoaiSPAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoaiSPAdminMouseEntered

    private void btnLoaiSPAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoaiSPAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoaiSPAdminMouseExited

    private void btnLoaiSPAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiSPAdminActionPerformed
        // TODO add your handling code here:
        shop.change("Loại Sản Phẩm");
        setSelectedBtn(btnLoaiSPAdmin);
        shop.setReturnIcon();
    }//GEN-LAST:event_btnLoaiSPAdminActionPerformed

    private void btnThongKeAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeAdminMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnThongKeAdminMouseClicked

    private void btnThongKeAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongKeAdminMouseEntered

    private void btnThongKeAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongKeAdminMouseExited

    private void btnThongKeAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeAdminActionPerformed
        // TODO add your handling code here:
        shop.change("Thống Kê");
        setSelectedBtn(btnThongKeAdmin);
        shop.setReturnIcon();
    }//GEN-LAST:event_btnThongKeAdminActionPerformed

    private void btnTimNangCaoAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimNangCaoAdminMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimNangCaoAdminMouseClicked

    private void btnTimNangCaoAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimNangCaoAdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimNangCaoAdminMouseEntered

    private void btnTimNangCaoAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimNangCaoAdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimNangCaoAdminMouseExited

    private void btnTimNangCaoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimNangCaoAdminActionPerformed
        // TODO add your handling code here:
        shop.change("Tìm Nâng Cao");
        setSelectedBtn(btnTimNangCaoAdmin);
        shop.setReturnIcon();
    }//GEN-LAST:event_btnTimNangCaoAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHangAdmin;
    private javax.swing.JButton btnKhachHangAdmin;
    private javax.swing.JButton btnKhuyenMaiAdmin;
    private javax.swing.JButton btnLoaiSPAdmin;
    private javax.swing.JButton btnNhaCungCapAdmin;
    private javax.swing.JButton btnNhaSanXuatAdmin;
    private javax.swing.JButton btnNhanVienAdmin;
    private javax.swing.JButton btnNhapHangAdmin;
    private javax.swing.JButton btnSanPhamAdmin;
    private javax.swing.JButton btnThongKeAdmin;
    private javax.swing.JButton btnTimNangCaoAdmin;
    private javax.swing.JScrollPane leftMenuScrollPane;
    private javax.swing.JPanel pnlLeftMenu4;
    // End of variables declaration//GEN-END:variables
}
