/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.MatteBorder;
import javax.swing.plaf.basic.BasicArrowButton;
import javax.swing.plaf.basic.BasicComboBoxUI;
import javax.swing.plaf.basic.BasicComboPopup;
import javax.swing.plaf.basic.ComboPopup;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kossp
 */
public class NhanVienFRM extends javax.swing.JPanel {

    /**
     * Creates new form NhanVienFRM
     */
    Color flatBlue = new Color(14,142,233);
    Color matteGrey = new Color(223,230,233);
    HoaDonFRM hd;
    TaiKhoanFRM tk;
    PhieuNhapFRM pn;
    
    public NhanVienFRM(PhieuNhapFRM pn,TaiKhoanFRM tk,HoaDonFRM hd) throws Exception {
        
        initComponents();
        tblScrollPane.getVerticalScrollBar().setUI(new MyScrollBarUI());
        comboBoxMucTimKiem = myComboBox(comboBoxMucTimKiem);
        tblNhanVien = initHeaderColor(tblNhanVien,14,142,233);
        DCNgaySinh = myDateChooser(DCNgaySinh);
        tblNhanVien.setDefaultEditor(Object.class, null);
        this.pn = pn;
        this.tk = tk;
        this.hd = hd;
        docDatabase();
        autoGenerateID();
        
    }
     public JDateChooser myDateChooser(JDateChooser chooser)
    {   
        JTextFieldDateEditor dateChooserEditor = ((JTextFieldDateEditor)chooser.getDateEditor());
        dateChooserEditor.setBackground(matteGrey);
        dateChooserEditor.setBorder(new MatteBorder(3,3,3,3,matteGrey));
        dateChooserEditor.setEditable(false);
        return chooser;
    }

     public JComboBox myComboBox(JComboBox box)
    {   
        box.setRenderer(new MyComboBoxRenderer());
        box.setEditor(new MyComboBoxEditor());
        
        box.setUI(new BasicComboBoxUI() 
        {
            @Override
            protected ComboPopup createPopup() 
            {
                BasicComboPopup basicComboPopup = new BasicComboPopup(comboBox);
                basicComboPopup.setBorder(new MatteBorder(4,4,4,4,flatBlue));
                return basicComboPopup;
            }
            
            @Override 
            protected JButton createArrowButton() 
            {
                Color matteGrey = new Color(223,230,233);
                Color flatBlue = new Color(14,142,233);
        
                BasicArrowButton custom = new BasicArrowButton(
                BasicArrowButton.SOUTH, null, null, Color.WHITE, null);
                custom.setBorder(new MatteBorder(0,0,0,0,flatBlue));
                return custom;
            }
        }); 

       return box;
    }
    public JTable initHeaderColor(JTable List,int r,int b, int g)
    {
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(r, b, g));
        headerRenderer.setForeground(Color.WHITE);
        
            for (int i = 0; i < List.getModel().getColumnCount(); i++) 
            {
                List.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
            }
        
         
        return List;
    }
    public void resetTxt() throws Exception {
        autoGenerateID();
        txtMaNV.setText("");
        txtHo.setText("");
        txtTen.setText("");
        txtDiaChi.setText("");
        txtLuong.setText("");
        btnNam.setSelected(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    DefaultTableModel model = new DefaultTableModel() ;
    DefaultTableModel modelTimKiem;

    boolean flag = true;

    public Vector createHeader(Object[] columnNames) {
        Vector header = new Vector();
        for (Object colName : columnNames) {
            header.add(colName);
        }

        return header;
    }

    public void docDatabase() throws Exception {
        NhanVienBUS bus = new NhanVienBUS();
        if (NhanVienBUS.getDsnv() == null) {
            bus.docDSNV();
        }

        String[] columnNames = {"Mã nhân viên", "Họ", "Tên", "Giới tính", "Ngày sinh", "Địa chỉ", "Lương"};
        Vector header = createHeader(columnNames);

        if (model.getRowCount() == 0) {
            model = new DefaultTableModel(header, 0);
        }

        for (NhanVienDTO nv : NhanVienBUS.getDsnv()) {
            Vector row = new Vector();
            row.add(nv.getMaNV());
            row.add(nv.getHo());
            row.add(nv.getTen());
            row.add(nv.getGioiTinh());
            row.add(nv.getNgaySinh());
            row.add(nv.getDiaChi());
            row.add(nv.getLuong());
            model.addRow(row);
        }

        tblNhanVien.setModel(model);
        tblNhanVien = initHeaderColor(tblNhanVien, 14, 142, 233);

    }
    public boolean checkEmptyTxt() {
        if (txtMaNV.getText().equals("") || txtHo.getText().equals("") || txtTen.getText().equals("") ||  txtDiaChi.getText().equals("") || txtLuong.getText().equals("") ) {
            return true;
        }
        return false;
    }
    
    void autoGenerateID() throws Exception
    {
        NhanVienBUS bus = new NhanVienBUS();
        String ID = bus.taoIdTuDong();
        txtMaNV.setText(ID);
    }

    public void hienCacNutChucNang() {
        btnThem.setEnabled(true);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
    }

    public void anCacNutChucNang() {
        btnThem.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GRPGioiTinh = new javax.swing.ButtonGroup();
        rightClickMenu = new javax.swing.JPopupMenu();
        xuatExcelFile = new javax.swing.JMenuItem();
        truyenExcelFile = new javax.swing.JMenuItem();
        pnlTable = new javax.swing.JPanel();
        tblScrollPane = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        pnlMain = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        lblHo = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtHo = new javax.swing.JTextField();
        pnlChucNang = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnHienThiTatCa = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        comboBoxMucTimKiem = new javax.swing.JComboBox<>();
        txtTen = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        DCNgaySinh = new com.toedter.calendar.JDateChooser();
        lblDiaChi = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        lblLuong = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        btnNam = new javax.swing.JRadioButton();
        btnNu = new javax.swing.JRadioButton();

        xuatExcelFile.setText("Export to excel file");
        xuatExcelFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuatExcelFileActionPerformed(evt);
            }
        });
        rightClickMenu.add(xuatExcelFile);

        truyenExcelFile.setText("Import from excel file\n");
        truyenExcelFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truyenExcelFileActionPerformed(evt);
            }
        });
        rightClickMenu.add(truyenExcelFile);

        pnlTable.setBackground(new java.awt.Color(255, 255, 255));

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseReleased(evt);
            }
        });
        tblScrollPane.setViewportView(tblNhanVien);

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tblScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setForeground(new java.awt.Color(14, 142, 233));
        pnlMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMainMouseClicked(evt);
            }
        });

        lblTieuDe.setBackground(new java.awt.Color(255, 255, 255));
        lblTieuDe.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(14, 142, 233));
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("NHÂN VIÊN");

        lblMaNV.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblMaNV.setForeground(new java.awt.Color(14, 142, 233));
        lblMaNV.setText("Mã nhân viên:");

        lblHo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblHo.setForeground(new java.awt.Color(14, 142, 233));
        lblHo.setText("Họ:");

        lblTen.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblTen.setForeground(new java.awt.Color(14, 142, 233));
        lblTen.setText("Tên:");

        lblGioiTinh.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(14, 142, 233));
        lblGioiTinh.setText("Giới tính:");

        txtMaNV.setBackground(new java.awt.Color(223, 230, 233));
        txtMaNV.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtMaNV.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(223, 230, 233)));

        txtHo.setBackground(new java.awt.Color(223, 230, 233));
        txtHo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtHo.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(223, 230, 233)));

        pnlChucNang.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setBackground(new java.awt.Color(14, 142, 233));
        btnThem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus_icon.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.setContentAreaFilled(false);
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.setIconTextGap(15);
        btnThem.setOpaque(true);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(14, 142, 233));
        btnXoa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash_icon.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.setBorder(null);
        btnXoa.setContentAreaFilled(false);
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.setIconTextGap(15);
        btnXoa.setOpaque(true);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(14, 142, 233));
        btnSua.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil_icon.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(null);
        btnSua.setContentAreaFilled(false);
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.setIconTextGap(15);
        btnSua.setOpaque(true);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChucNangLayout = new javax.swing.GroupLayout(pnlChucNang);
        pnlChucNang.setLayout(pnlChucNangLayout);
        pnlChucNangLayout.setHorizontalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChucNangLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        pnlChucNangLayout.setVerticalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnHienThiTatCa.setBackground(new java.awt.Color(14, 142, 233));
        btnHienThiTatCa.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnHienThiTatCa.setForeground(new java.awt.Color(255, 255, 255));
        btnHienThiTatCa.setText("Hiển thị tất cả");
        btnHienThiTatCa.setBorder(null);
        btnHienThiTatCa.setContentAreaFilled(false);
        btnHienThiTatCa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHienThiTatCa.setOpaque(true);
        btnHienThiTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiTatCaActionPerformed(evt);
            }
        });

        txtTimKiem.setBackground(new java.awt.Color(223, 230, 233));
        txtTimKiem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtTimKiem.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(223, 230, 233)));

        btnTimKiem.setBackground(new java.awt.Color(14, 142, 233));
        btnTimKiem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_icon.png"))); // NOI18N
        btnTimKiem.setBorder(null);
        btnTimKiem.setContentAreaFilled(false);
        btnTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimKiem.setOpaque(true);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        comboBoxMucTimKiem.setBackground(new java.awt.Color(14, 142, 233));
        comboBoxMucTimKiem.setEditable(true);
        comboBoxMucTimKiem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        comboBoxMucTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxMucTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã NV", "Họ", "Tên", "Giới tính", "Ngày sinh", "Địa chỉ", "Lương" }));
        comboBoxMucTimKiem.setToolTipText("null");
        comboBoxMucTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboBoxMucTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMucTimKiemActionPerformed(evt);
            }
        });

        txtTen.setBackground(new java.awt.Color(223, 230, 233));
        txtTen.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtTen.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(223, 230, 233)));

        lblNgaySinh.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(14, 142, 233));
        lblNgaySinh.setText("Ngày sinh:");

        DCNgaySinh.setBackground(new java.awt.Color(223, 230, 233));
        DCNgaySinh.setDateFormatString("y-MM-d");
        DCNgaySinh.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lblDiaChi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(14, 142, 233));
        lblDiaChi.setText("Địa chỉ:");

        txtLuong.setBackground(new java.awt.Color(223, 230, 233));
        txtLuong.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtLuong.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(223, 230, 233)));

        lblLuong.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblLuong.setForeground(new java.awt.Color(14, 142, 233));
        lblLuong.setText("Lương:");

        txtDiaChi.setBackground(new java.awt.Color(223, 230, 233));
        txtDiaChi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtDiaChi.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(223, 230, 233)));

        GRPGioiTinh.add(btnNam);
        btnNam.setSelected(true);
        btnNam.setText("Nam");
        btnNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNamActionPerformed(evt);
            }
        });

        GRPGioiTinh.add(btnNu);
        btnNu.setText("Nữ");
        btnNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTen))
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNam)
                                .addGap(18, 18, 18)
                                .addComponent(btnNu)
                                .addGap(0, 48, Short.MAX_VALUE))
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaNV)
                                    .addComponent(txtHo))))
                        .addGap(29, 29, 29))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(btnHienThiTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(comboBoxMucTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DCNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DCNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNgaySinh)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDiaChi))
                            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblHo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTen)
                            .addComponent(txtTen)
                            .addComponent(lblLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGioiTinh)
                            .addComponent(btnNam)
                            .addComponent(btnNu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)))
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHienThiTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBoxMucTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxMucTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMucTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxMucTimKiemActionPerformed

    private void btnNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNamActionPerformed

    private void btnNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuActionPerformed

    private void pnlMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMainMouseClicked
        try {
            // TODO add your handling code here:
            resetTxt();
        } catch (Exception ex) {
            Logger.getLogger(NhanVienFRM.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblNhanVien.clearSelection();
    }//GEN-LAST:event_pnlMainMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (checkEmptyTxt() == true)
            return;
        else {
            NhanVienBUS bus = new NhanVienBUS();

            if (bus.kiemTraTrung(txtMaNV.getText())) {
                JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại. Mời nhập Mã nhân viên khác!");
                return;
            }

            NhanVienDTO nv = new NhanVienDTO();
            Date date = DCNgaySinh.getDate();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String strDate = df.format(date);
            nv.setNgaySinh(strDate);
            
            nv.setMaNV(txtMaNV.getText());
            nv.setHo(txtHo.getText());
            nv.setTen(txtTen.getText());
            if(btnNam.isSelected())
            {
                nv.setGioiTinh(btnNam.getText());
            }
            if(btnNu.isSelected())
            {
                nv.setGioiTinh(btnNu.getText());
            }

            nv.setDiaChi(txtDiaChi.getText());
            nv.setLuong(Float.valueOf(txtLuong.getText()));

            try {
                bus.them(nv);
            } catch (Exception ex) {
                Logger.getLogger(NhanVienFRM.class.getName()).log(Level.SEVERE, null, ex);
            }

            String[] columnNames = {"Mã nhân viên", "Họ", "Tên", "Giới tính", "Ngày sinh", "Địa chỉ", "Lương"};
            Vector header = createHeader(columnNames);

            if (model.getRowCount() == 0) {
                model = new DefaultTableModel(header, 0);
            }

            Vector row = new Vector();
            row.add(nv.getMaNV());
            row.add(nv.getHo());
            row.add(nv.getTen());
            row.add(nv.getGioiTinh());
            row.add(nv.getNgaySinh());
            row.add(nv.getDiaChi());
            row.add(nv.getLuong());

            model.addRow(row);
            tblNhanVien.setModel(model);

            String [] arrayNV = new String[NhanVienBUS.getDsnv().size()];
                try {
                  arrayNV = bus.docComboBoxMaNV();
                } catch (Exception ex) {
                    Logger.getLogger(NhanVienFRM.class.getName()).log(Level.SEVERE, null, ex);
                }
            try {
                pn.docComboBoxNV(arrayNV);
                tk.docComboBoxNV(arrayNV);               
                hd.docComboBoxNV(arrayNV);
            } catch (Exception ex) {
                Logger.getLogger(NhanVienFRM.class.getName()).log(Level.SEVERE, null, ex);
            }             
           
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            try {
                resetTxt();
            } catch (Exception ex) {
                Logger.getLogger(NhanVienFRM.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnHienThiTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiTatCaActionPerformed
        // TODO add your handling code here:
        flag = true;
        tblNhanVien.setModel(model);
        btnThem.setEnabled(true);
        tblNhanVien = initHeaderColor(tblNhanVien, 14, 142, 233);
    }//GEN-LAST:event_btnHienThiTatCaActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        int i = tblNhanVien.getSelectedRow();
        if (i >= 0) {
            NhanVienBUS bus = new NhanVienBUS();
            NhanVienDTO nv = new NhanVienDTO();
            if (flag == true) {
                nv = NhanVienBUS.getDsnv().get(i);
            } else {
                int index = bus.timIndex(modelTimKiem.getValueAt(i, 0).toString());
                nv = NhanVienBUS.getDsnv().get(index);
            }
            
            if(nv.getGioiTinh().equals("Nam"))
            {
                btnNam.setSelected(true);
            }
            if(nv.getGioiTinh().equals("Nữ"))
            {
                btnNu.setSelected(true);
            }
            
            txtMaNV.setText(nv.getMaNV());
            txtHo.setText(nv.getHo());
            txtTen.setText(nv.getTen()); 
            txtDiaChi.setText(nv.getDiaChi());
            txtLuong.setText(Float.toString(nv.getLuong()));
            String ngay = nv.getNgaySinh();
            try {
                Date Ngay = new SimpleDateFormat("yyyy-MM-dd").parse(ngay);
                DCNgaySinh.setDate(Ngay);
            } catch (ParseException ex) {
                Logger.getLogger(NhanVienFRM.class.getName()).log(Level.SEVERE, null, ex);
            }
            btnXoa.setEnabled(true);
            btnSua.setEnabled(true);
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int i = tblNhanVien.getSelectedRow();
        if (i >= 0) {
            int selection = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa dòng này?", "Thông báo xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (selection == JOptionPane.YES_OPTION) {
                NhanVienBUS bus = new NhanVienBUS();
                if (flag == true)
                {
                    String maNV = model.getValueAt(i, 0).toString();
                    try {
                        bus.xoa(maNV);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Bạn không thể xóa dòng này!");
                        return;
                    }

                    model.removeRow(i);
                    tblNhanVien.setModel(model);
                }
                else
                {
                    String maNV = modelTimKiem.getValueAt(i, 0).toString();
                    try {
                        bus.xoa(maNV);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Bạn không thể xóa dòng này!");
                        
                        return;
                    }

                    int index = bus.timIndex(maNV);

                    modelTimKiem.removeRow(i);
                    tblNhanVien.setModel(modelTimKiem);

                    model.removeRow(index);
                }

                btnXoa.setEnabled(false);
                btnSua.setEnabled(false);
                
                String [] arrayNV = new String[NhanVienBUS.getDsnv().size()];
                try {
                  arrayNV = bus.docComboBoxMaNV();
                } catch (Exception ex) {
                    Logger.getLogger(NhanVienFRM.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    pn.docComboBoxNV(arrayNV);
                    tk.docComboBoxNV(arrayNV);
                    hd.docComboBoxNV(arrayNV);
                } catch (Exception ex) {
                    Logger.getLogger(NhanVienFRM.class.getName()).log(Level.SEVERE, null, ex);
                }          
                
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                try {
                    resetTxt();
                } catch (Exception ex) {
                    Logger.getLogger(NhanVienFRM.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int temp = -1;
        int i = tblNhanVien.getSelectedRow();
        if (i >= 0) {
            NhanVienBUS bus = new NhanVienBUS();
            String maNVCu;
            if (flag == true) {
                maNVCu = model.getValueAt(i, 0).toString();
            } else {
                temp = i;
                maNVCu = modelTimKiem.getValueAt(temp, 0).toString();
                i = bus.timIndex(maNVCu);
            }

            if (bus.kiemTraTrung(txtMaNV.getText(), maNVCu)) {
                JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại. Mời nhập Mã nhân viên khác!");
                return;
            } else {

                NhanVienDTO nv = new NhanVienDTO();
                Date date = DCNgaySinh.getDate();
                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                String strDate = df.format(date);

                nv.setMaNV(txtMaNV.getText());
                nv.setHo(txtHo.getText());
                nv.setTen(txtTen.getText());
                if(btnNam.isSelected())
                {
                    nv.setGioiTinh(btnNam.getText());
                }
                if(btnNu.isSelected())
                {
                    nv.setGioiTinh(btnNu.getText());
                }
                nv.setNgaySinh(strDate);
                nv.setDiaChi(txtDiaChi.getText());
                nv.setLuong(Float.parseFloat(txtLuong.getText()));


                NhanVienDTO old = NhanVienBUS.getDsnv().get(i);

                try {
                    bus.sua(nv, old);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Bạn không thể thay đổi Mã nhân viên này!");
                    return;
                }

                model.setValueAt(nv.getMaNV(), i, 0);
                model.setValueAt(nv.getHo(), i, 1);
                model.setValueAt(nv.getTen(), i, 2);
                model.setValueAt(nv.getGioiTinh(), i, 3);
                model.setValueAt(nv.getNgaySinh(), i, 4);
                model.setValueAt(nv.getDiaChi(), i, 5);
                model.setValueAt(nv.getLuong(), i, 6);

                if (flag == false) {
                    modelTimKiem.setValueAt(nv.getMaNV(), temp, 0);
                    modelTimKiem.setValueAt(nv.getHo(), temp, 1);
                    modelTimKiem.setValueAt(nv.getTen(), temp, 2);
                    modelTimKiem.setValueAt(nv.getGioiTinh(), temp, 3);
                    modelTimKiem.setValueAt(nv.getNgaySinh(), temp, 4);
                    modelTimKiem.setValueAt(nv.getDiaChi(), temp, 5);
                    modelTimKiem.setValueAt(nv.getLuong(), temp, 6);
                }

                hienCacNutChucNang();

                String [] arrayNV = new String[NhanVienBUS.getDsnv().size()];
                try {
                  arrayNV = bus.docComboBoxMaNV();
                } catch (Exception ex) {
                    Logger.getLogger(NhanVienFRM.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    pn.docComboBoxNV(arrayNV);
                    tk.docComboBoxNV(arrayNV);
                    hd.docComboBoxNV(arrayNV);
                } catch (Exception ex) {
                    Logger.getLogger(NhanVienFRM.class.getName()).log(Level.SEVERE, null, ex);
                }          
                
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
                try {
                    resetTxt();
                } catch (Exception ex) {
                    Logger.getLogger(NhanVienFRM.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String mucTimKiem = comboBoxMucTimKiem.getSelectedItem().toString();
        String duLieu = txtTimKiem.getText();

        String[] columnNames = {"Mã nhân viên", "Họ", "Tên", "Giới tính","Ngày sinh", "Địa chỉ", "Lương"};
        Vector header = createHeader(columnNames);

        if (duLieu.equals("") == false) {
            ArrayList<NhanVienDTO> tempArr = new ArrayList<NhanVienDTO>();
            NhanVienBUS bus = new NhanVienBUS();

            tempArr = bus.timKiem(mucTimKiem, duLieu);

            if (tempArr.size() > 0) {
                modelTimKiem = new DefaultTableModel();

                if (modelTimKiem.getRowCount() == 0) {
                    modelTimKiem = new DefaultTableModel(header, 0);
                }

                for (NhanVienDTO nv : tempArr) {
                    Vector row = new Vector();
                    row.add(nv.getMaNV());
                    row.add(nv.getHo());
                    row.add(nv.getTen());
                    row.add(nv.getGioiTinh());
                    row.add(nv.getNgaySinh());
                    row.add(nv.getDiaChi());
                    row.add(nv.getLuong());

                    modelTimKiem.addRow(row);
                }
                tblNhanVien.setModel(modelTimKiem);
                tblNhanVien = initHeaderColor(tblNhanVien, 14, 142, 233);

                flag = false;
                anCacNutChucNang();

            } else {
                JOptionPane.showMessageDialog(this, "Rất tiếc. Dữ liệu không được tìm thấy!");
            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void xuatExcelFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuatExcelFileActionPerformed
        String[] columnNames = {"Mã nhân viên", "Họ", "Tên", "Giới tính","Ngày sinh", "Địa chỉ", "Lương"};
        try {
            XuatExcel xuat = new XuatExcel(tblNhanVien, columnNames, "Nhân Viên");
        } catch (IOException ex) {
            Logger.getLogger(KhachHangFRM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_xuatExcelFileActionPerformed

    private void tblNhanVienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseReleased
        if(evt.isPopupTrigger())
        {
            rightClickMenu.show(tblNhanVien, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblNhanVienMouseReleased

    private void truyenExcelFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truyenExcelFileActionPerformed

        nhapExcel nhap = new nhapExcel(tblNhanVien);
        DefaultTableModel newModel = nhap.importExcel();
        if(newModel.getRowCount() > 0)
        {
            tblNhanVien.setModel(newModel);
            tblNhanVien = initHeaderColor(tblNhanVien, 14, 142, 233);
        }
    }//GEN-LAST:event_truyenExcelFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DCNgaySinh;
    private javax.swing.ButtonGroup GRPGioiTinh;
    private javax.swing.JButton btnHienThiTatCa;
    private javax.swing.JRadioButton btnNam;
    private javax.swing.JRadioButton btnNu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> comboBoxMucTimKiem;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHo;
    private javax.swing.JLabel lblLuong;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlChucNang;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JPopupMenu rightClickMenu;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JScrollPane tblScrollPane;
    private javax.swing.JMenuItem truyenExcelFile;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JMenuItem xuatExcelFile;
    // End of variables declaration//GEN-END:variables
}
