/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;
import static com.sun.java.accessibility.util.AWTEventMonitor.addWindowListener;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.border.MatteBorder;
import javax.swing.plaf.basic.BasicArrowButton;
import javax.swing.plaf.basic.BasicComboBoxUI;
import javax.swing.plaf.basic.BasicComboPopup;
import javax.swing.plaf.basic.ComboPopup;
import javax.swing.table.DefaultTableCellRenderer;
import com.toedter.calendar.JDateChooser;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author loith
 */
public class ChiTietHDFrame extends javax.swing.JFrame {
    Color matteGrey = new Color(223,230,233);
    Color flatBlue = new Color(14,142,233);
    /**
     * Creates new form ChiTietHDFrame
     */
    
    HoaDonFRM parent;
    SanPhamFRM spFRM;
    boolean parentAllBtnClicked;
    
    public ChiTietHDFrame(ShopForm shop, String maHD) throws Exception {
        initComponents();
        this.parent = shop.getHoaDonFRM();
        this.spFRM = shop.getSanPhamFRM();
        tblScrollPane.getVerticalScrollBar().setUI(new MyScrollBarUI());;
        tblChiTietHD = initHeaderColor(tblChiTietHD,14,142,233); 
        comboBoxMucTimKiem = myComboBox(comboBoxMucTimKiem, flatBlue);
        docComboBox();
        setTxtDonGia(ComboBoxMaSP.getSelectedItem().toString());
        if(maHD == null)
            parentAllBtnClicked = true;
        else
            parentAllBtnClicked = false;
        tblChiTietHD = setColumnWidth(tblChiTietHD);
        docDatabase(maHD);
        tblChiTietHD = initHeaderColor(tblChiTietHD, 14, 142, 233);
    }

    private ChiTietHDFrame(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
     public void resetTxt() throws Exception {
        txtSoLuong.setText("");
    }
    
     public JTable setColumnWidth(JTable table)
    {      
        return table;
    }
     
    public JDateChooser myDateChooser(JDateChooser chooser)
    {   
        JTextFieldDateEditor dateChooserEditor = ((JTextFieldDateEditor)chooser.getDateEditor());
        dateChooserEditor.setBackground(matteGrey);
        dateChooserEditor.setBorder(new MatteBorder(3,3,3,3,matteGrey));
        dateChooserEditor.setEditable(false);
        return chooser;
    }
    
    public JComboBox myComboBox(JComboBox box, Color color)
    {   
        box.setRenderer(new MyComboBoxRenderer());
        box.setEditor(new MyComboBoxEditor());
        
        box.setUI(new BasicComboBoxUI() 
        {
            @Override
            protected ComboPopup createPopup() 
            {
                BasicComboPopup basicComboPopup = new BasicComboPopup(comboBox);
                basicComboPopup.setBorder(new MatteBorder(4,4,4,4,color));
                return basicComboPopup;
            }
            
            @Override 
            protected JButton createArrowButton() 
            {
                Color matteGrey = new Color(223,230,233);
                Color flatBlue = new Color(14,142,233);
        
                BasicArrowButton custom = new BasicArrowButton(
                BasicArrowButton.SOUTH, null, null, Color.WHITE, null);
                custom.setBorder(new MatteBorder(0,0,0,0,flatBlue));
                return custom;
            }
        }); 

       return box;
    }
    public JTable initHeaderColor(JTable List,int r,int b, int g)
    {
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(r, b, g));
        headerRenderer.setForeground(Color.WHITE);
        
            for (int i = 0; i < List.getModel().getColumnCount(); i++) 
            {
                List.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
            }
        
         
        return List;
    }
    
    public void setTxtDonGia(String maSP)
    {
        SanPhamBUS spBus = new SanPhamBUS();
        txtDonGia.setText(Float.toString(spBus.timSP(maSP).getDonGia()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightClickMenu1 = new javax.swing.JPopupMenu();
        xuatExcelFile1 = new javax.swing.JMenuItem();
        nhapExcelFile = new javax.swing.JMenuItem();
        pnlMain = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        lblMaHD = new javax.swing.JLabel();
        lblMaSP = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        pnlChucNang = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnHienThiTatCa = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        comboBoxMucTimKiem = new javax.swing.JComboBox<>();
        lblDonGia = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        ComboBoxMaSP = new javax.swing.JComboBox<>();
        ComboBoxMaHD = new javax.swing.JComboBox<>();
        pnlTable = new javax.swing.JPanel();
        tblScrollPane = new javax.swing.JScrollPane();
        tblChiTietHD = new javax.swing.JTable();

        xuatExcelFile1.setText("Export to excel file");
        xuatExcelFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuatExcelFile1ActionPerformed(evt);
            }
        });
        rightClickMenu1.add(xuatExcelFile1);

        nhapExcelFile.setText("Import Excel File\n");
        nhapExcelFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapExcelFileActionPerformed(evt);
            }
        });
        rightClickMenu1.add(nhapExcelFile);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setForeground(new java.awt.Color(14, 142, 233));
        pnlMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMainMouseClicked(evt);
            }
        });

        lblTieuDe.setBackground(new java.awt.Color(255, 255, 255));
        lblTieuDe.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(14, 142, 233));
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("Chi tiết hoá đơn");

        lblMaHD.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblMaHD.setForeground(new java.awt.Color(14, 142, 233));
        lblMaHD.setText("Mã hoá đơn:");

        lblMaSP.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblMaSP.setForeground(new java.awt.Color(14, 142, 233));
        lblMaSP.setText("Mã sản phẩm:");

        lblSoLuong.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblSoLuong.setForeground(new java.awt.Color(14, 142, 233));
        lblSoLuong.setText("Số lượng:");

        pnlChucNang.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setBackground(new java.awt.Color(14, 142, 233));
        btnThem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus_icon.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.setContentAreaFilled(false);
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.setIconTextGap(15);
        btnThem.setOpaque(true);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(14, 142, 233));
        btnXoa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash_icon.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.setBorder(null);
        btnXoa.setContentAreaFilled(false);
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.setEnabled(false);
        btnXoa.setIconTextGap(15);
        btnXoa.setOpaque(true);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(14, 142, 233));
        btnSua.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil_icon.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(null);
        btnSua.setContentAreaFilled(false);
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.setEnabled(false);
        btnSua.setIconTextGap(15);
        btnSua.setOpaque(true);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChucNangLayout = new javax.swing.GroupLayout(pnlChucNang);
        pnlChucNang.setLayout(pnlChucNangLayout);
        pnlChucNangLayout.setHorizontalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChucNangLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        pnlChucNangLayout.setVerticalGroup(
            pnlChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChucNangLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnHienThiTatCa.setBackground(new java.awt.Color(14, 142, 233));
        btnHienThiTatCa.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnHienThiTatCa.setForeground(new java.awt.Color(255, 255, 255));
        btnHienThiTatCa.setText("Hiển thị tất cả");
        btnHienThiTatCa.setBorder(null);
        btnHienThiTatCa.setContentAreaFilled(false);
        btnHienThiTatCa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHienThiTatCa.setOpaque(true);
        btnHienThiTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiTatCaActionPerformed(evt);
            }
        });

        txtTimKiem.setBackground(new java.awt.Color(223, 230, 233));
        txtTimKiem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtTimKiem.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(223, 230, 233)));

        btnTimKiem.setBackground(new java.awt.Color(14, 142, 233));
        btnTimKiem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_icon.png"))); // NOI18N
        btnTimKiem.setBorder(null);
        btnTimKiem.setContentAreaFilled(false);
        btnTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimKiem.setOpaque(true);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        comboBoxMucTimKiem.setBackground(new java.awt.Color(14, 142, 233));
        comboBoxMucTimKiem.setEditable(true);
        comboBoxMucTimKiem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        comboBoxMucTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxMucTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã HĐ", "Mã SP", "Số lượng", "Đơn giá" }));
        comboBoxMucTimKiem.setToolTipText("null");
        comboBoxMucTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboBoxMucTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMucTimKiemActionPerformed(evt);
            }
        });

        lblDonGia.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblDonGia.setForeground(new java.awt.Color(14, 142, 233));
        lblDonGia.setText("Đơn giá:");

        txtSoLuong.setBackground(new java.awt.Color(223, 230, 233));
        txtSoLuong.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtSoLuong.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(223, 230, 233)));
        txtSoLuong.setPreferredSize(new java.awt.Dimension(7, 24));

        txtDonGia.setEditable(false);
        txtDonGia.setBackground(new java.awt.Color(223, 230, 233));
        txtDonGia.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtDonGia.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(223, 230, 233)));
        txtDonGia.setPreferredSize(new java.awt.Dimension(7, 24));

        ComboBoxMaSP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxMaSPItemStateChanged(evt);
            }
        });
        ComboBoxMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMaSPActionPerformed(evt);
            }
        });

        ComboBoxMaHD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxMaHDItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMaHD))
                                .addGap(157, 157, 157)
                                .addComponent(lblDonGia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnHienThiTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGap(308, 308, 308)
                                .addComponent(comboBoxMucTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBoxMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDonGia)
                                .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnlChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHienThiTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxMucTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnlTable.setBackground(new java.awt.Color(255, 255, 255));

        tblChiTietHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblChiTietHD.setSelectionBackground(new java.awt.Color(14, 142, 233));
        tblChiTietHD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblChiTietHDFocusLost(evt);
            }
        });
        tblChiTietHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietHDMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblChiTietHDMouseReleased(evt);
            }
        });
        tblScrollPane.setViewportView(tblChiTietHD);

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tblScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel model = new DefaultTableModel();;
    DefaultTableModel modelTimKiem;
    boolean flag = true;

    public Vector createHeader(Object[] columnNames) {
        Vector header = new Vector();
        for (Object colName : columnNames) {
            header.add(colName);
        }

        return header;
    }
    
    public void docDatabase(String maHD) throws Exception {
        String[] columnNames = {"Mã hoá đơn", "Mã sản phẩm", "Số lượng", "Đơn giá"};
        Vector header = createHeader(columnNames);

        if (model.getRowCount() == 0) {
            model = new DefaultTableModel(header, 0);
        }
        
        ChiTietHDBUS bus = new ChiTietHDBUS();
        
        if(maHD == null)
        {
            bus.docDSCTHD();
        }
        else 
        {
            bus.docCTHD(maHD);
            ComboBoxMaHD.setSelectedItem(maHD);
            ComboBoxMaHD.setEnabled(false);
        }

        for (ChiTietHDDTO cthd : ChiTietHDBUS.getDscthd()) {
            Vector row = new Vector();
            row.add(cthd.getMaHD());
            row.add(cthd.getMaSP());
            row.add(cthd.getSoLuong());
            row.add(cthd.getDonGia());
    
            model.addRow(row);
        }

        tblChiTietHD.setModel(model);
        tblChiTietHD = initHeaderColor(tblChiTietHD, 14, 142, 233);

    }
    
    public void docComboBox() throws Exception{
        SanPhamBUS busSP = new SanPhamBUS();
        HoaDonBUS busHD = new HoaDonBUS();
        String[] arrayMaSP = busSP.docComboBoxMaSP();
        String[] arrayMaHD = busHD.docComboBoxMaHD();
        ComboBoxMaSP.setModel(new javax.swing.DefaultComboBoxModel<>(arrayMaSP));
        ComboBoxMaSP = myComboBox(ComboBoxMaSP,matteGrey);
        ComboBoxMaHD.setModel(new javax.swing.DefaultComboBoxModel<>(arrayMaHD));
        ComboBoxMaHD = myComboBox(ComboBoxMaHD,matteGrey);
    }
    
    public void docComboBoxMaSP(String ma[]) throws Exception{
        ComboBoxMaSP.setModel(new javax.swing.DefaultComboBoxModel<>(ma));
    }
    
    public boolean checkEmptyTxt() {
        if (txtSoLuong.getText().equals("") || txtDonGia.getText().equals(""))
            return true;
        return false;
    }
 
    public void hienCacNutChucNang() {
        btnThem.setEnabled(true);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
    }

    public void anCacNutChucNang() {
        btnThem.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (checkEmptyTxt() == true)
        return;
        else {
            ChiTietHDBUS bus = new ChiTietHDBUS();

            if (bus.kiemTraTrung(ComboBoxMaHD.getSelectedItem().toString(),ComboBoxMaSP.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(this, "Mã hóa đơn và Mã sản phẩm đã tồn tại. Mời nhập Mã hóa đơn và Mã sản phẩm khác!");
                return;
            }

            ChiTietHDDTO cthd = new ChiTietHDDTO();
            cthd.setMaHD(ComboBoxMaHD.getSelectedItem().toString());
            cthd.setMaSP(ComboBoxMaSP.getSelectedItem().toString());
            cthd.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
            cthd.setDonGia(Float.parseFloat(txtDonGia.getText())); 

            SanPhamBUS spBus = new SanPhamBUS();
            try {
                if(spBus.laySP(cthd.getMaSP(), cthd.getSoLuong()) == true)
                {
                    try {
                        bus.them(cthd);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Mã HD không tồn tại!");
                        return;
                    }
                    
                    String[] columnNames = {"Mã hoá đơn", "Mã sản phẩm", "Số lượng", "Đơn giá"};
                    Vector header = createHeader(columnNames);
                    
                    if (model.getRowCount() == 0) {
                        model = new DefaultTableModel(header, 0);
                    }
                    
                    Vector row = new Vector();
                    row.add(cthd.getMaHD());
                    row.add(cthd.getMaSP());
                    row.add(cthd.getSoLuong());
                    row.add(cthd.getDonGia());
                    
                    model.addRow(row);
                    tblChiTietHD.setModel(model);
                    
                    spFRM.refreshTableRowSoLuong(cthd.getMaSP());
                    
                    HoaDonBUS hdBus = new HoaDonBUS();
                    try {
                        parent.resetMoney(cthd.getMaHD(), hdBus.timHD(cthd.getMaHD()).getMaKM());
                    } catch (Exception ex) {
                        Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    JOptionPane.showMessageDialog(this, "Thêm thành công!");
                    try {
                        resetTxt();
                    } catch (Exception ex) {
                        Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Rất tiếc! Số lượng sản phẩm bạn yêu cầu trong kho chỉ còn " + spBus.timSP(cthd.getMaSP()).getSoLuong());
                }
            } catch (Exception ex) {
                Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int i = tblChiTietHD.getSelectedRow();
        if (i >= 0) {
            int selection = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa dòng này?", "Thông báo xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (selection == JOptionPane.YES_OPTION) {
                String ma_sp;
                int so_luong;
                
                ChiTietHDBUS bus = new ChiTietHDBUS();
                if (flag == true)
                {
                    String maHD = model.getValueAt(i, 0).toString();
                    String maSP = model.getValueAt(i, 1).toString();
                    
                    ma_sp = maSP;
                    so_luong = bus.timCTHD(maHD, maSP).getSoLuong();
                    
                    try {
                        bus.xoa(maHD,maSP);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Bạn không thể xóa dòng này!");
                        return;
                    }

                    model.removeRow(i); 
                    tblChiTietHD.setModel(model);
                    
                    HoaDonBUS hdBus = new HoaDonBUS();
                    try {
                        parent.resetMoney(maHD, hdBus.timHD(maHD).getMaKM());
                    } catch (Exception ex) {
                        Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    KhuyenMaiHopLeBUS kmhlBus = new KhuyenMaiHopLeBUS();
                    try {
                        if(kmhlBus.timDSKMHL(maHD).size() == 0)
                            try {
                                parent.xoaKM(maHD);
                            } catch (Exception ex) {
                                Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                            }
                    } catch (Exception ex) {
                        Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                {
                    String maHD = modelTimKiem.getValueAt(i, 0).toString();
                    String maSP = modelTimKiem.getValueAt(i, 1).toString();
                    
                    ma_sp = maSP;
                    so_luong = bus.timCTHD(maHD, maSP).getSoLuong();
                    
                    try {
                        bus.xoa(maHD,maSP);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Bạn không thể xóa dòng này!");
                        return;
                    }

                    int index = bus.timIndex(maHD,maSP);

                    modelTimKiem.removeRow(i);
                    tblChiTietHD.setModel(modelTimKiem);

                    model.removeRow(index);
                    
                    HoaDonBUS hdBus = new HoaDonBUS();
                    try {
                        parent.resetMoney(maHD, hdBus.timHD(maHD).getMaKM());
                    } catch (Exception ex) {
                        Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    KhuyenMaiHopLeBUS kmhlBus = new KhuyenMaiHopLeBUS();
                    try {
                        if(kmhlBus.timDSKMHL(maHD).size() == 0)
                            try {
                                parent.xoaKM(maHD);
                            } catch (Exception ex) {
                                Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                            }
                    } catch (Exception ex) {
                        Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                SanPhamBUS spBus = new SanPhamBUS();
                try {
                    spBus.nhapSP(ma_sp, so_luong);
                } catch (Exception ex) {
                    Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                spFRM.refreshTableRowSoLuong(ma_sp);

                btnXoa.setEnabled(false);
                btnSua.setEnabled(false);
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                try {
                    resetTxt();
                } catch (Exception ex) {
                    Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int temp = -1;
        int i = tblChiTietHD.getSelectedRow();
        if (i >= 0) {
            ChiTietHDBUS bus = new ChiTietHDBUS();
            String maHDCu;
            String maSPCu;
            if (flag == true) {
                maHDCu = model.getValueAt(i, 0).toString();
                maSPCu = model.getValueAt(i, 1).toString();
            } else {
                temp = i;
                maHDCu = modelTimKiem.getValueAt(temp, 0).toString();
                maSPCu = modelTimKiem.getValueAt(temp, 1).toString();
                i = bus.timIndex(maHDCu,maSPCu);
            }

            if (bus.kiemTraTrung(ComboBoxMaHD.getSelectedItem().toString(), maHDCu, ComboBoxMaSP.getSelectedItem().toString(), maSPCu)) {
                JOptionPane.showMessageDialog(this, "Mã hóa đơn và Mã sản phẩm đã tồn tại. Mời nhập Mã hóa đơn và Mã sản phẩm khác!");
                return;
            } else {

                ChiTietHDDTO cthd = new ChiTietHDDTO();
                cthd.setMaHD(ComboBoxMaHD.getSelectedItem().toString());
                cthd.setMaSP(ComboBoxMaSP.getSelectedItem().toString());
                cthd.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
                cthd.setDonGia(Float.parseFloat(txtDonGia.getText())); 

                ChiTietHDDTO old = ChiTietHDBUS.getDscthd().get(i);
                
                String ma_sp_cu = maSPCu;
                int so_luong_cu = old.getSoLuong();
                
                String ma_sp_moi = cthd.getMaSP();
                int so_luong_moi = cthd.getSoLuong();
                
                try {
                    bus.sua(cthd, old);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Bạn không thể thay đổi Mã hoá đơn và mã sản phẩm này!");
                    return;
                }
                
                SanPhamBUS spBus = new SanPhamBUS();
                try {
                    spBus.nhapSP(ma_sp_cu, so_luong_cu);
                } catch (Exception ex) {
                    Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                spFRM.refreshTableRowSoLuong(ma_sp_cu);
                
                try {
                    spBus.laySP(ma_sp_moi, so_luong_moi);
                } catch (Exception ex) {
                    Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                spFRM.refreshTableRowSoLuong(ma_sp_moi);

                model.setValueAt(cthd.getMaHD(), i, 0);
                model.setValueAt(cthd.getMaSP(), i, 1);
                model.setValueAt(cthd.getSoLuong(), i, 2);
                model.setValueAt(cthd.getDonGia(), i, 3);

                if (flag == false) {
                    modelTimKiem.setValueAt(cthd.getMaHD(), temp, 0);
                    modelTimKiem.setValueAt(cthd.getMaSP(), temp, 1);
                    modelTimKiem.setValueAt(cthd.getSoLuong(), temp, 2);
                    modelTimKiem.setValueAt(cthd.getDonGia(), temp, 3);
                }
                
                HoaDonBUS hdBus = new HoaDonBUS();
                try {
                    parent.resetMoney(cthd.getMaHD(), hdBus.timHD(cthd.getMaHD()).getMaKM());
                } catch (Exception ex) {
                    Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                KhuyenMaiHopLeBUS kmhlBus = new KhuyenMaiHopLeBUS();
                try {
                    if(kmhlBus.timDSKMHL(cthd.getMaHD()).size() == 0)
                        try {
                            parent.xoaKM(cthd.getMaHD());
                        } catch (Exception ex) {
                            Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                } catch (Exception ex) {
                    Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                hienCacNutChucNang();

                JOptionPane.showMessageDialog(this, "Sửa thành công!");
                try {
                    resetTxt();
                } catch (Exception ex) {
                    Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String mucTimKiem = comboBoxMucTimKiem.getSelectedItem().toString();
        String duLieu = txtTimKiem.getText();

        String[] columnNames = {"Mã HĐ", "MaSP", "Số lượng", "Đơn giá"};
        Vector header = createHeader(columnNames);

        if (duLieu.equals("") == false) {
            ArrayList<ChiTietHDDTO> tempArr = new ArrayList<ChiTietHDDTO>();
            ChiTietHDBUS bus = new ChiTietHDBUS();

            tempArr = bus.timKiem(mucTimKiem, duLieu);

            if (tempArr.size() > 0) {
                modelTimKiem = new DefaultTableModel();

                if (modelTimKiem.getRowCount() == 0) {
                    modelTimKiem = new DefaultTableModel(header, 0);
                }

                for (ChiTietHDDTO cthd : tempArr) {
                    Vector row = new Vector();
                    row.add(cthd.getMaHD());
                    row.add(cthd.getMaSP());
                    row.add(cthd.getSoLuong());
                    row.add(cthd.getDonGia());

                    modelTimKiem.addRow(row);
                }
                tblChiTietHD.setModel(modelTimKiem);
                tblChiTietHD = initHeaderColor(tblChiTietHD, 14, 142, 233);

                flag = false;
                anCacNutChucNang();

            } else {
                JOptionPane.showMessageDialog(this, "Rất tiếc. Dữ liệu không được tìm thấy!");
            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void comboBoxMucTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMucTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxMucTimKiemActionPerformed

    private void pnlMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMainMouseClicked
        try {
            // TODO add your handling code here:
            resetTxt();
        } catch (Exception ex) {
            Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblChiTietHD.clearSelection();
    }//GEN-LAST:event_pnlMainMouseClicked

    private void tblChiTietHDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblChiTietHDFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_tblChiTietHDFocusLost

    private void tblChiTietHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietHDMouseClicked
        int i = tblChiTietHD.getSelectedRow();
        if (i >= 0) {
            ChiTietHDDTO cthd = new ChiTietHDDTO();
            if (flag == true) {
                cthd.setMaHD(model.getValueAt(i, 0).toString());
                cthd.setMaSP(model.getValueAt(i, 1).toString());
                cthd.setSoLuong((int) model.getValueAt(i, 2));
                cthd.setDonGia((float) model.getValueAt(i, 3));
            } else {
                cthd.setMaHD(modelTimKiem.getValueAt(i, 0).toString());
                cthd.setMaSP(modelTimKiem.getValueAt(i, 1).toString());
                cthd.setSoLuong((int) modelTimKiem.getValueAt(i, 2));
                cthd.setDonGia((float) modelTimKiem.getValueAt(i, 3));
            }

            ComboBoxMaHD.setSelectedItem(cthd.getMaHD());
            ComboBoxMaSP.setSelectedItem(cthd.getMaSP());
            txtSoLuong.setText(Integer.toString(cthd.getSoLuong()));
            txtDonGia.setText(Float.toString(cthd.getDonGia())); 

            btnXoa.setEnabled(true);
            btnSua.setEnabled(true);
        }
    }//GEN-LAST:event_tblChiTietHDMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
         
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void btnHienThiTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiTatCaActionPerformed
        flag = true;
        tblChiTietHD.setModel(model);
        btnThem.setEnabled(true);
        tblChiTietHD = initHeaderColor(tblChiTietHD, 14, 142, 233);
    }//GEN-LAST:event_btnHienThiTatCaActionPerformed

    private void ComboBoxMaSPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxMaSPItemStateChanged
        setTxtDonGia(ComboBoxMaSP.getSelectedItem().toString());
    }//GEN-LAST:event_ComboBoxMaSPItemStateChanged

    private void ComboBoxMaHDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxMaHDItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMaHDItemStateChanged

    private void ComboBoxMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMaSPActionPerformed

    private void xuatExcelFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuatExcelFile1ActionPerformed
        String[] columnNames = {"Mã PN", "Mã SP", "Số lượng", "Đơn giá"};
        try {
            XuatExcel xuat = new XuatExcel(tblChiTietHD, columnNames, "Chi Tiết Phiếu Nhập");
        } catch (IOException ex) {
            Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_xuatExcelFile1ActionPerformed

    private void tblChiTietHDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietHDMouseReleased
        if(evt.isPopupTrigger())
        {
            rightClickMenu1.show(tblChiTietHD, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblChiTietHDMouseReleased

    private void nhapExcelFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapExcelFileActionPerformed
        // TODO add your handling code here:
        nhapExcel nhap = new nhapExcel(tblChiTietHD);
        DefaultTableModel newModel = nhap.importExcel();
        if(newModel.getRowCount() > 0)
        {
            tblChiTietHD.setModel(newModel);
            tblChiTietHD = initHeaderColor(tblChiTietHD, 14, 142, 233);
        }
    }//GEN-LAST:event_nhapExcelFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietHDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietHDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietHDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietHDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ChiTietHDFrame(null).setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ChiTietHDFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxMaHD;
    private javax.swing.JComboBox<String> ComboBoxMaSP;
    private javax.swing.JButton btnHienThiTatCa;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> comboBoxMucTimKiem;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblMaHD;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JMenuItem nhapExcelFile;
    private javax.swing.JPanel pnlChucNang;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JPopupMenu rightClickMenu1;
    private javax.swing.JTable tblChiTietHD;
    private javax.swing.JScrollPane tblScrollPane;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JMenuItem xuatExcelFile1;
    // End of variables declaration//GEN-END:variables
}
